"""Add footer settings to Settings model

Revision ID: 0590c4572ef1
Revises: 7ae53bc9acc0
Create Date: 2025-09-12 11:15:17.232391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0590c4572ef1'
down_revision = '7ae53bc9acc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('footer_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('footer_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('footer_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('footer_instagram_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('footer_facebook_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('footer_whatsapp_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('footer_copyright_text', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('footer_copyright_text')
        batch_op.drop_column('footer_whatsapp_link')
        batch_op.drop_column('footer_facebook_link')
        batch_op.drop_column('footer_instagram_link')
        batch_op.drop_column('footer_email')
        batch_op.drop_column('footer_phone')
        batch_op.drop_column('footer_address')

    # ### end Alembic commands ###
