"""Adiciona tabela Lead para contatos

Revision ID: 0db2e245681a
Revises: e06674f6a265
Create Date: 2025-09-01 15:01:49.296137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db2e245681a'
down_revision = 'e06674f6a265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('child_name', sa.String(length=100), nullable=True),
    sa.Column('child_age', sa.Integer(), nullable=True),
    sa.Column('service_of_interest', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead')
    # ### end Alembic commands ###
