"""Add business name and description to settings

Revision ID: 0f2210693b65
Revises: eee08a47f3be
Create Date: 2025-09-16 09:19:38.928792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2210693b65'
down_revision = 'eee08a47f3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('site_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('site_description')
        batch_op.drop_column('business_name')

    # ### end Alembic commands ###
