"""Add feature flags and hero colors to homepage

Revision ID: 145fd6da325e
Revises: 16a89adacdca
Create Date: 2025-09-12 08:32:48.532015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145fd6da325e'
down_revision = '16a89adacdca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_page_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_services_card1', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_services_card2', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_services_card3', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_page_content', schema=None) as batch_op:
        batch_op.drop_column('show_services_card3')
        batch_op.drop_column('show_services_card2')
        batch_op.drop_column('show_services_card1')

    # ### end Alembic commands ###
