"""Simplify homepage feature flags to main sections only

Revision ID: 15eaa318f1a9
Revises: 145fd6da325e
Create Date: 2025-09-12 08:47:08.825673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15eaa318f1a9'
down_revision = '145fd6da325e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_page_content', schema=None) as batch_op:
        batch_op.drop_column('show_services_card3')
        batch_op.drop_column('show_services_card1')
        batch_op.drop_column('show_services_card2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_page_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_services_card2', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('show_services_card1', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('show_services_card3', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
