"""Add feature flags and hero colors to homepage

Revision ID: 16a89adacdca
Revises: 8ed2e1195f81
Create Date: 2025-09-12 08:17:54.555247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a89adacdca'
down_revision = '8ed2e1195f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_page_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_hero_section', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hero_background_color_from', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hero_background_color_to', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('show_services_section', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_values_section', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_structure_section', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_blog_section', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_cta_section', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_location_section', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_page_content', schema=None) as batch_op:
        batch_op.drop_column('show_location_section')
        batch_op.drop_column('show_cta_section')
        batch_op.drop_column('show_blog_section')
        batch_op.drop_column('show_structure_section')
        batch_op.drop_column('show_values_section')
        batch_op.drop_column('show_services_section')
        batch_op.drop_column('hero_background_color_to')
        batch_op.drop_column('hero_background_color_from')
        batch_op.drop_column('show_hero_section')

    # ### end Alembic commands ###
