"""Add LandingPage model

Revision ID: 29cb3457c5af
Revises: 0db2e245681a
Create Date: 2025-09-02 14:16:04.739536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cb3457c5af'
down_revision = '0db2e245681a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature_block')
    with op.batch_alter_table('landing_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hero_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('hero_subtitle', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hero_image', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hero_cta_text', sa.String(length=50), nullable=True, help_text="Texto do botão, ex: 'Saiba Mais'"))
        batch_op.add_column(sa.Column('hero_cta_link', sa.String(length=255), nullable=True, help_text='Link de destino do botão'))
        batch_op.add_column(sa.Column('content_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('content_body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_image', sa.String(length=100), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_landing_page_is_published'), ['is_published'], unique=False)
        batch_op.drop_column('cta_text')
        batch_op.drop_column('hero_image_filename')
        batch_op.drop_column('cta_url')
        batch_op.drop_column('subheadline')
        batch_op.drop_column('headline')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landing_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headline', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('subheadline', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('cta_url', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('hero_image_filename', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('cta_text', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_index(batch_op.f('ix_landing_page_is_published'))
        batch_op.alter_column('slug',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('content_image')
        batch_op.drop_column('content_body')
        batch_op.drop_column('content_title')
        batch_op.drop_column('hero_cta_link')
        batch_op.drop_column('hero_cta_text')
        batch_op.drop_column('hero_image')
        batch_op.drop_column('hero_subtitle')
        batch_op.drop_column('hero_title')
        batch_op.drop_column('is_published')

    op.create_table('feature_block',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('image_filename', sa.VARCHAR(length=100), nullable=True),
    sa.Column('image_position', sa.VARCHAR(length=10), nullable=True),
    sa.Column('landing_page_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['landing_page_id'], ['landing_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
