"""Cria modelos para conteúdo da homepage

Revision ID: 3fe06ed40d42
Revises: c1b1a4d23c9b
Create Date: 2025-09-09 12:22:18.484371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe06ed40d42'
down_revision = 'c1b1a4d23c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_page_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_title', sa.String(length=200), nullable=True),
    sa.Column('hero_subtitle', sa.Text(), nullable=True),
    sa.Column('services_title', sa.String(length=200), nullable=True),
    sa.Column('services_subtitle', sa.Text(), nullable=True),
    sa.Column('values_title', sa.String(length=200), nullable=True),
    sa.Column('values_subtitle', sa.Text(), nullable=True),
    sa.Column('mission_text', sa.Text(), nullable=True),
    sa.Column('vision_text', sa.Text(), nullable=True),
    sa.Column('values_item_text', sa.Text(), nullable=True),
    sa.Column('structure_title', sa.String(length=200), nullable=True),
    sa.Column('structure_subtitle', sa.Text(), nullable=True),
    sa.Column('cta_title', sa.String(length=200), nullable=True),
    sa.Column('cta_subtitle', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('structure_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('caption', sa.String(length=100), nullable=False),
    sa.Column('homepage_content_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homepage_content_id'], ['home_page_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('roles_permissions')
    op.drop_table('role')
    op.drop_table('permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_permissions',
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.drop_table('structure_image')
    op.drop_table('home_page_content')
    # ### end Alembic commands ###
