"""Cria tabela de Configuracoes

Revision ID: 4332152b299a
Revises: 6938492d1f67
Create Date: 2025-09-02 19:17:23.837482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4332152b299a'
down_revision = '6938492d1f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_whatsapp_message', sa.Text(), nullable=True),
    sa.Column('client_whatsapp_message', sa.Text(), nullable=True),
    sa.Column('birthday_congrats_message', sa.Text(), nullable=True),
    sa.Column('birthday_notification_days', sa.Integer(), nullable=True, help_text='Número de dias de antecedência para destacar aniversariantes.'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
