"""Add is_approved and update role default in User model

Revision ID: 579aff53ae65
Revises: 0f2210693b65
Create Date: 2025-09-16 09:44:08.276429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579aff53ae65'
down_revision = '0f2210693b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), server_default='f', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
