"""Adiciona campo de status aos Leads

Revision ID: 5e80eb940d3c
Revises: 29cb3457c5af
Create Date: 2025-09-02 16:25:46.385154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e80eb940d3c'
down_revision = '29cb3457c5af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
