"""Cria tabela de Clientes

Revision ID: 6938492d1f67
Revises: 5e80eb940d3c
Create Date: 2025-09-02 17:04:48.425213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6938492d1f67'
down_revision = '5e80eb940d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_name', sa.String(length=150), nullable=False),
    sa.Column('child_date_of_birth', sa.Date(), nullable=False),
    sa.Column('parent1_name', sa.String(length=150), nullable=False),
    sa.Column('parent1_phone', sa.String(length=20), nullable=False),
    sa.Column('parent2_name', sa.String(length=150), nullable=True),
    sa.Column('parent2_phone', sa.String(length=20), nullable=True),
    sa.Column('address_street', sa.String(length=200), nullable=True),
    sa.Column('address_number', sa.String(length=20), nullable=True),
    sa.Column('address_neighborhood', sa.String(length=100), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_cep', sa.String(length=10), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
