"""Add section_order to HomePageContent

Revision ID: 7ae53bc9acc0
Revises: 15eaa318f1a9
Create Date: 2025-09-12 09:07:10.802659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae53bc9acc0'
down_revision = '15eaa318f1a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_page_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_order', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_page_content', schema=None) as batch_op:
        batch_op.drop_column('section_order')

    # ### end Alembic commands ###
