"""Create Popup model

Revision ID: 7b95c9e31cb4
Revises: 0590c4572ef1
Create Date: 2025-09-15 18:21:27.387581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b95c9e31cb4'
down_revision = '0590c4572ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('popup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False, comment='Título interno para identificação no dashboard.'),
    sa.Column('image_filename', sa.String(length=100), nullable=False, comment='Nome do arquivo da imagem.'),
    sa.Column('target_url', sa.String(length=255), nullable=False, comment='Link de destino ao clicar na imagem.'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Só pode haver um popup ativo por vez.'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('popup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_popup_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('popup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_popup_is_active'))

    op.drop_table('popup')
    # ### end Alembic commands ###
