"""New bd

Revision ID: 8b95bbbd82f2
Revises: 
Create Date: 2025-09-19 16:00:57.098480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b95bbbd82f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_name', sa.String(length=150), nullable=False),
    sa.Column('child_date_of_birth', sa.Date(), nullable=False),
    sa.Column('parent1_name', sa.String(length=150), nullable=False),
    sa.Column('parent1_phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('parent2_name', sa.String(length=150), nullable=True),
    sa.Column('parent2_phone', sa.String(length=20), nullable=True),
    sa.Column('address_street', sa.String(length=200), nullable=True),
    sa.Column('address_number', sa.String(length=20), nullable=True),
    sa.Column('address_neighborhood', sa.String(length=100), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_cep', sa.String(length=10), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=False)

    op.create_table('home_page_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_order', sa.Text(), server_default='hero,services,values,structure,videos,blog,cta,location', nullable=False),
    sa.Column('show_hero_section', sa.Boolean(), nullable=True),
    sa.Column('hero_background_color_from', sa.String(length=20), nullable=True),
    sa.Column('hero_background_color_to', sa.String(length=20), nullable=True),
    sa.Column('hero_badge_text', sa.String(length=200), nullable=True),
    sa.Column('hero_title', sa.String(length=200), nullable=True),
    sa.Column('hero_subtitle', sa.Text(), nullable=True),
    sa.Column('hero_whatsapp_button_text', sa.String(length=100), nullable=True),
    sa.Column('hero_whatsapp_button_link', sa.String(length=255), nullable=True),
    sa.Column('hero_highlight_text', sa.String(length=200), nullable=True),
    sa.Column('show_services_section', sa.Boolean(), nullable=True),
    sa.Column('services_section_tagline', sa.String(length=100), nullable=True),
    sa.Column('services_section_title', sa.String(length=200), nullable=True),
    sa.Column('services_section_subtitle', sa.Text(), nullable=True),
    sa.Column('services_card1_icon', sa.String(length=10), nullable=True),
    sa.Column('services_card1_title', sa.String(length=100), nullable=True),
    sa.Column('services_card1_text', sa.Text(), nullable=True),
    sa.Column('services_card1_item1', sa.String(length=100), nullable=True),
    sa.Column('services_card1_item2', sa.String(length=100), nullable=True),
    sa.Column('services_card1_item3', sa.String(length=100), nullable=True),
    sa.Column('services_card1_cta_text', sa.String(length=50), nullable=True),
    sa.Column('services_card1_cta_link', sa.String(length=255), nullable=True),
    sa.Column('services_card2_icon', sa.String(length=10), nullable=True),
    sa.Column('services_card2_title', sa.String(length=100), nullable=True),
    sa.Column('services_card2_text', sa.Text(), nullable=True),
    sa.Column('services_card2_item1', sa.String(length=100), nullable=True),
    sa.Column('services_card2_item2', sa.String(length=100), nullable=True),
    sa.Column('services_card2_item3', sa.String(length=100), nullable=True),
    sa.Column('services_card2_cta_text', sa.String(length=50), nullable=True),
    sa.Column('services_card2_cta_link', sa.String(length=255), nullable=True),
    sa.Column('services_card3_icon', sa.String(length=10), nullable=True),
    sa.Column('services_card3_title', sa.String(length=100), nullable=True),
    sa.Column('services_card3_text', sa.Text(), nullable=True),
    sa.Column('services_card3_item1', sa.String(length=100), nullable=True),
    sa.Column('services_card3_item2', sa.String(length=100), nullable=True),
    sa.Column('services_card3_item3', sa.String(length=100), nullable=True),
    sa.Column('services_card3_cta_text', sa.String(length=50), nullable=True),
    sa.Column('services_card3_cta_link', sa.String(length=255), nullable=True),
    sa.Column('show_values_section', sa.Boolean(), nullable=True),
    sa.Column('values_section_tagline', sa.String(length=100), nullable=True),
    sa.Column('values_section_title', sa.String(length=200), nullable=True),
    sa.Column('values_section_subtitle', sa.Text(), nullable=True),
    sa.Column('values_card1_icon', sa.String(length=10), nullable=True),
    sa.Column('values_card1_title', sa.String(length=100), nullable=True),
    sa.Column('values_card1_text', sa.Text(), nullable=True),
    sa.Column('values_card2_icon', sa.String(length=10), nullable=True),
    sa.Column('values_card2_title', sa.String(length=100), nullable=True),
    sa.Column('values_card2_text', sa.Text(), nullable=True),
    sa.Column('values_card3_icon', sa.String(length=10), nullable=True),
    sa.Column('values_card3_title', sa.String(length=100), nullable=True),
    sa.Column('values_card3_text', sa.Text(), nullable=True),
    sa.Column('show_structure_section', sa.Boolean(), nullable=True),
    sa.Column('structure_section_tagline', sa.String(length=100), nullable=True),
    sa.Column('structure_section_title', sa.String(length=200), nullable=True),
    sa.Column('structure_section_subtitle', sa.Text(), nullable=True),
    sa.Column('structure_feature1_title', sa.String(length=100), nullable=True),
    sa.Column('structure_feature1_text', sa.Text(), nullable=True),
    sa.Column('structure_feature2_title', sa.String(length=100), nullable=True),
    sa.Column('structure_feature2_text', sa.Text(), nullable=True),
    sa.Column('show_blog_section', sa.Boolean(), nullable=True),
    sa.Column('blog_section_tagline', sa.String(length=100), nullable=True),
    sa.Column('blog_section_title', sa.String(length=200), nullable=True),
    sa.Column('blog_section_subtitle', sa.Text(), nullable=True),
    sa.Column('blog_cta_text', sa.String(length=100), nullable=True),
    sa.Column('show_cta_section', sa.Boolean(), nullable=True),
    sa.Column('cta_title', sa.String(length=200), nullable=True),
    sa.Column('cta_subtitle', sa.Text(), nullable=True),
    sa.Column('cta_whatsapp_button_text', sa.String(length=100), nullable=True),
    sa.Column('cta_form_button_text', sa.String(length=100), nullable=True),
    sa.Column('show_location_section', sa.Boolean(), nullable=True),
    sa.Column('location_section_tagline', sa.String(length=100), nullable=True),
    sa.Column('location_section_title', sa.String(length=200), nullable=True),
    sa.Column('location_section_subtitle', sa.Text(), nullable=True),
    sa.Column('location_card_title', sa.String(length=100), nullable=True),
    sa.Column('location_address_title', sa.String(length=50), nullable=True),
    sa.Column('location_address_text', sa.Text(), nullable=True),
    sa.Column('location_phone_title', sa.String(length=50), nullable=True),
    sa.Column('location_phone_text', sa.String(length=50), nullable=True),
    sa.Column('location_hours_title', sa.String(length=50), nullable=True),
    sa.Column('location_hours_text', sa.Text(), nullable=True),
    sa.Column('location_gmaps_button_text', sa.String(length=50), nullable=True),
    sa.Column('location_gmaps_link', sa.String(length=255), nullable=True),
    sa.Column('location_image_alt', sa.String(length=200), nullable=True),
    sa.Column('show_videos_section', sa.Boolean(), nullable=True),
    sa.Column('videos_section_title', sa.String(length=200), nullable=True),
    sa.Column('videos_section_video1', sa.String(length=100), nullable=True),
    sa.Column('videos_section_video2', sa.String(length=100), nullable=True),
    sa.Column('videos_section_video3', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landing_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False, comment='Título interno da página para organização.'),
    sa.Column('slug', sa.String(length=120), nullable=False, comment='A URL final da página (ex: /lp/nome-da-campanha).'),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('hero_title', sa.String(length=200), nullable=True),
    sa.Column('hero_subtitle', sa.Text(), nullable=True),
    sa.Column('hero_image', sa.String(length=100), nullable=True),
    sa.Column('hero_cta_text', sa.String(length=50), nullable=True, comment="Texto do botão, ex: 'Saiba Mais'"),
    sa.Column('hero_cta_link', sa.String(length=255), nullable=True, comment='Link de destino do botão'),
    sa.Column('content_title', sa.String(length=200), nullable=True),
    sa.Column('content_body', sa.Text(), nullable=True),
    sa.Column('content_image', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('landing_page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_landing_page_is_published'), ['is_published'], unique=False)

    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('child_name', sa.String(length=100), nullable=True),
    sa.Column('child_age', sa.Integer(), nullable=True),
    sa.Column('service_of_interest', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('popup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False, comment='Título interno para identificação no dashboard.'),
    sa.Column('image_filename', sa.String(length=100), nullable=False, comment='Nome do arquivo da imagem.'),
    sa.Column('target_url', sa.String(length=255), nullable=False, comment='Link de destino ao clicar na imagem.'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Só pode haver um popup ativo por vez.'),
    sa.Column('display_mode', sa.String(length=50), nullable=False, comment="Modo de exibição: 'show_once' (mostrar uma vez) ou 'always_show' (mostrar sempre)."),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('popup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_popup_is_active'), ['is_active'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=True),
    sa.Column('site_description', sa.Text(), nullable=True),
    sa.Column('lead_whatsapp_message', sa.Text(), nullable=True),
    sa.Column('client_whatsapp_message', sa.Text(), nullable=True),
    sa.Column('birthday_congrats_message', sa.Text(), nullable=True),
    sa.Column('birthday_notification_days', sa.Integer(), nullable=True, comment='Número de dias de antecedência para destacar aniversariantes.'),
    sa.Column('footer_address', sa.Text(), nullable=True),
    sa.Column('footer_phone', sa.String(length=50), nullable=True),
    sa.Column('footer_email', sa.String(length=120), nullable=True),
    sa.Column('footer_instagram_link', sa.String(length=255), nullable=True),
    sa.Column('footer_facebook_link', sa.String(length=255), nullable=True),
    sa.Column('footer_whatsapp_link', sa.String(length=255), nullable=True),
    sa.Column('footer_copyright_text', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_approved', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('client_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=150), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('video_filename', sa.String(length=100), nullable=True),
    sa.Column('meta_description', sa.String(length=160), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('structure_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('caption', sa.String(length=100), nullable=False),
    sa.Column('homepage_content_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homepage_content_id'], ['home_page_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('structure_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('caption', sa.String(length=100), nullable=False),
    sa.Column('homepage_content_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['homepage_content_id'], ['home_page_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_categories',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'category_id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('post_categories')
    op.drop_table('image')
    op.drop_table('structure_video')
    op.drop_table('structure_image')
    op.drop_table('post')
    op.drop_table('client_service')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('settings')
    with op.batch_alter_table('popup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_popup_is_active'))

    op.drop_table('popup')
    op.drop_table('lead')
    with op.batch_alter_table('landing_page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_landing_page_is_published'))

    op.drop_table('landing_page')
    op.drop_table('home_page_content')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_email'))

    op.drop_table('client')
    op.drop_table('category')
    # ### end Alembic commands ###
