"""Adiciona campo cover_image ao Post

Revision ID: 934c7ee2f84b
Revises: ed144ee165a3
Create Date: 2025-08-31 07:06:46.177185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934c7ee2f84b'
down_revision = 'ed144ee165a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
