"""Adiciona modelos LandingPage e FeatureBlock

Revision ID: e06674f6a265
Revises: 934c7ee2f84b
Create Date: 2025-08-31 17:08:18.459411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06674f6a265'
down_revision = '934c7ee2f84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=False),
    sa.Column('subheadline', sa.Text(), nullable=True),
    sa.Column('hero_image_filename', sa.String(length=100), nullable=True),
    sa.Column('cta_text', sa.String(length=50), nullable=False),
    sa.Column('cta_url', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('feature_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_filename', sa.String(length=100), nullable=True),
    sa.Column('image_position', sa.String(length=10), nullable=True),
    sa.Column('landing_page_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landing_page_id'], ['landing_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature_block')
    op.drop_table('landing_page')
    # ### end Alembic commands ###
