"""Add display_mode to Popup model

Revision ID: eee08a47f3be
Revises: 7b95c9e31cb4
Create Date: 2025-09-15 18:44:22.251946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee08a47f3be'
down_revision = '7b95c9e31cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('popup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_mode', sa.String(length=50), nullable=False, comment="Modo de exibição: 'show_once' (mostrar uma vez) ou 'always_show' (mostrar sempre)."))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('popup', schema=None) as batch_op:
        batch_op.drop_column('display_mode')

    # ### end Alembic commands ###
